name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install lua5.2 luarocks
    - name: Dependencies
      run: |
        luarocks install --local moonscript
        luarocks install --local busted
        luarocks install --local luasocket
    - name: Test
      run: busted
