name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install lua5.1 lua5.1-dev luarocks
    - name: Dependencies
      run: ./install_rocks.sh github
    - name: Test
      run: busted -c
    - name: Coverage
      run: luacov-coveralls -t ${{ secrets.COVERALLS_TOKEN }}
